In [7]:
from scipy.fft import fft, ifft
import numpy as np
from scipy import linalg

In [8]:
x = np.array([1.0, 2.0, 1.0, -1.0, 1.5])
y = fft(x)
y

array([ 4.5       -0.j        ,  2.08155948-1.65109876j,
       -1.83155948+1.60822041j, -1.83155948-1.60822041j,
        2.08155948+1.65109876j])

In [9]:
yinv = ifft(y)
yinv

array([ 1. +0.j,  2. +0.j,  1. +0.j, -1. +0.j,  1.5+0.j])

In [10]:
a = np.array([[1,2], [3,4]])
a

array([[1, 2],
       [3, 4]])

In [12]:
b = linalg.inv(a)
b

array([[-2. ,  1. ],
       [ 1.5, -0.5]])