In [2]:
import numpy as np

In [3]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
a.shape

(3, 5)

In [5]:
a.ndim

2

In [6]:
b = np.array([1.2, 3.5, 5.1])
b.dtype

dtype('float64')

In [7]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
ones_arr = np.ones((2,2), dtype=np.int32)
ones_arr

array([[1, 1],
       [1, 1]])

In [9]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [10]:
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [11]:
a = np.arange(10)**3
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [19]:
rg = np.random.default_rng(1)
a = np.floor(10*rg.random((3, 4)))
a

array([[5., 9., 1., 9.],
       [3., 4., 8., 4.],
       [5., 0., 7., 5.]])

In [21]:
a.reshape((6,2))

array([[5., 9.],
       [1., 9.],
       [3., 4.],
       [8., 4.],
       [5., 0.],
       [7., 5.]])